export const emojis = {
  "+1":                                   "👍",
	"-1":                                   "👎",
  "muscle":                               "💪",
  "facepunch":                            "👊",
  "anguished":                            "😧",
  "astonished":                           "😲",
  "blonde_woman":                         "👱‍♀",
  "blush":                                "😊",
  "cold_sweat":                           "😰",
  "confounded":                           "😖",
	"confused":                             "😕",
  "cry":                                  "😢",
	"disappointed":                         "😞",
	"disappointed_relieved":                "😥",
	"dizzy_face":                           "😵",
  "drooling_face":                        "🤤",
  "expressionless":                       "😑",
  "face_with_head_bandage":               "🤕",
	"face_with_thermometer":                "🤒",
  "fearful":                              "😨",
  "frowning":                             "😦",
	"frowning_face":                        "☹️",
  "full_moon_with_face":                  "🌝",
  "grimacing":                            "😬",
	"grin":                                 "😁",
	"grinning":                             "😀",
}